---
apiVersion: v1
data:
  POSTGRES_DB: postgresdb
  POSTGRES_PASSWORD: password
  POSTGRES_USER: admin
  SPRING_DATASOURCE_PASSWORD: password
  SPRING_DATASOURCE_URL: jdbc:postgresql://ledger-db:5432/postgresdb
  SPRING_DATASOURCE_USERNAME: admin
kind: ConfigMap
metadata:
  labels:
    app: postgres
  name: ledger-db-config
  namespace: default
