---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    client.lifecycle.config.k8s.io/mutation: ignore
  labels:
    app.kubernetes.io/instance: bank-of-anthos
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: bank-of-anthos
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: bank-of-anthos-0.1.0
  name: bank-of-anthos
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: bank-of-anthos
      app.kubernetes.io/name: bank-of-anthos
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: bank-of-anthos
        app.kubernetes.io/name: bank-of-anthos
    spec:
      containers:
      - image: nginx:1.16.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: http
        name: bank-of-anthos
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources: {}
        securityContext: {}
      securityContext: {}
      serviceAccountName: bank-of-anthos
