---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: bank-of-anthos
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: bank-of-anthos
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: bank-of-anthos-0.1.0
  name: bank-of-anthos
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: bank-of-anthos
    app.kubernetes.io/name: bank-of-anthos
  type: ClusterIP
