---
apiVersion: v1
kind: Service
metadata:
  name: ledger-db
  namespace: default
spec:
  ports:
  - name: tcp
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: ledger-db
  type: ClusterIP
