---
apiVersion: v1
kind: Service
metadata:
  name: contacts
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: contacts
  type: ClusterIP
