---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test
  labels:
    app.kubernetes.io/instance: bank-of-anthos
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: bank-of-anthos
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: bank-of-anthos-0.1.0
  name: bank-of-anthos-test-connection
spec:
  containers:
  - args:
    - bank-of-anthos:80
    command:
    - wget
    image: busybox
    name: wget
  restartPolicy: Never
