---
apiVersion: v1
kind: Service
metadata:
  name: balancereader
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: balancereader
  type: ClusterIP
