---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: accounts-db
    tier: db
  name: accounts-db
spec:
  ports:
  - name: tcp
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: accounts-db
    tier: db
